### ISSUE TITLE
How to skip assemblies in generation?

### ISSUE THREAD

**Issue by KonH** [neuecc/MarkdownGenerator#4]
Is any way to skip some documentation generation in your tool? I am trying to use it for Unity project and faced to large output which is not required for my case, it is dependencies, no sense to include it to my docs. Yes, I can ignore concrete files, but index contains it too.
May be any workaround already exists? Thanks for your answer!

**Comment by neuecc** [comment]
you can filter to add this line.
https://github.com/neuecc/MarkdownGenerator/blob/master/MarkdownGenerator.cs#L240

**Comment by KonH** [comment]
Thanks for response!
I have made pull-request with namespace regex filter, you can approve it, if it is can make your tool better to use - https://github.com/neuecc/MarkdownGenerator/pull/5
